Repository grafana/grafana-image-renderer, pull requests merged in 2024-05, with the labels that each got.

#517 Chore: Remove unused dependencies
  package.json
  yarn.lock
Labels: type/chore

#524 Full page image: fix scrolling with the new native scroll
  jest.config.js
  scripts/drone/provisioning/dashboards/all-panels.json
  src/browser/browser.ts
  src/service/http-server.integration.test.ts
  tests/testdata/full-page-screenshot.png
Labels: type/bug

#527 Server: Support HTTPS configuration
  default.json
  src/service/config.ts
  src/service/http-server.ts
Labels: component/service, security
