Repository grafana/grafana-image-renderer, pull requests merged in 2024-08, with the labels that each got.

#552 Scroll correct element when `bodyScrolling` is enabled
  src/browser/browser.ts
Labels: type/bug

#554 Full page image: Fix blank page
  src/browser/browser.ts
Labels: type/bug, component/puppeteer

#556 Puppeteer: Upgrade to v22
  package.json
  scripts/download_chrome.js
  scripts/run_tests.sh
  src/app.ts
  src/browser/browser.ts
  src/browser/reusable.ts
  src/service/http-server.integration.test.ts
  tests/testdata/error.png
  tests/testdata/full-page-screenshot.png
  tests/testdata/graph.png
  tests/testdata/table.png
  yarn.lock
Labels: type/chore
